Session 3A1

In [2]:
import numpy as np

a)The List A conist of int and float type values,since the numpy array can only hold the homonegeous values so the values are converted into float and stored in numpy array

In [3]:
A = [1, 2, 3, 4.0]
print(A)

[1, 2, 3, 4.0]


In [4]:
npA = np.array(A)
print(npA)

[1. 2. 3. 4.]


### `type()` function in Python

b)The `type()` function in Python is used to determine the type of an object. It returns the class type of the object passed to it. You can use `type()` to check whether a variable is a list, integer, string, float, NumPy array, or any other data type.

In [5]:
print('Type of npA is ', type(npA))

Type of npA is  <class 'numpy.ndarray'>


c)`ndim` gives you the number of dimensions in a NumPy array

In [6]:
print("Dimension of npA is ", npA.ndim)

Dimension of npA is  1


In [7]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Dimension of arr3 is ", arr3.ndim)

Dimension of arr3 is  3


d)`shape` It returns a tuple with ints giving the no. of element in each dimension

In [8]:
print("Shape of nPA is ", npA.shape)

Shape of nPA is  (4,)


In [9]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

The shape of `arr3` is `(2, 2, 2)`, which means:

1. There are **2 blocks** (outermost level).

   - The two blocks are:
     ```
     Block 1: [[1, 2], [3, 4]]
     Block 2: [[5, 6], [7, 8]]
     ```

2. Each block contains **2 rows** (second level).

   - For **Block 1**, the rows are:
     ```
     [1, 2]
     [3, 4]
     ```
   
   - For **Block 2**, the rows are:
     ```
     [5, 6]
     [7, 8]
     ```

3. Each row has **2 elements** (innermost level).

   - For **Block 1**, the elements in each row are:
     ```
     Row 1: [1, 2]
     Row 2: [3, 4]
     ```

   - For **Block 2**, the elements in each row are:
     ```
     Row 1: [5, 6]
     Row 2: [7, 8]
     ```


In [10]:
print("Shape of arr3 is ", arr3.shape)

Shape of arr3 is  (2, 2, 2)


e)The `size` attribute is used to return the total number of elements in a NumPy array. It calculates the product of all the dimensions of the array, regardless of the shape

In [11]:
print("Size of npA ", npA.size)

Size of npA  4


In [12]:
print("Size of arr3",arr3.size)

Size of arr3 8


f)`dtype`

In [13]:
print("Data type of elements in npA ", npA.dtype)

Data type of elements in npA  float64


g)`itemsize`

Note: In Python float is 8bytes

Python uses double-precision floating-point format (also known as float64), which allocates 64 bits to store a float

In [14]:
print("Memory size of each element in npA ", npA.itemsize)

Memory size of each element in npA  8


h)Total size of npA =npA.size * npA.itemsize

In [15]:
print("Total size of npA in bytes is ", npA.size * npA.itemsize)

Total size of npA in bytes is  32


In [16]:
A2_3 = [[1, 2, 3], [4, 5, 6]]
print(A2_3)

[[1, 2, 3], [4, 5, 6]]


In [17]:
npA2_3 = np.array(A2_3)
print(npA2_3)

[[1 2 3]
 [4 5 6]]


i)`np.append()`

This line attempts to append the list [7, 8, 9] to the array npA2_3. However, since npA2_3 is a 2D array and [7, 8, 9] is a 1D array, NumPy will flatten npA2_3 before the append operation, resulting in a new 1D array

NumPy provides several methods to flatten an array:
1) flatten(): This method returns a copy of the array collapsed into one dimension.
2) ravel(): This method also returns a flattened array, but it returns a view whenever possible, which is more memory efficient.
3) np.append(): When using this function on a multi-dimensional array with a 1D array, NumPy flattens the original array before appending.

In [18]:
npA = np.append(npA2_3, [7, 8, 9])
print(npA)

[1 2 3 4 5 6 7 8 9]


Note: The axis=0 parameter specifies that the append operation should be performed along the rows (the vertical axis). In other words, you are adding the new row to the bottom of the existing array.

In [19]:
npA3_3 = np.append(npA2_3, [[7, 8, 9]], axis=0)
print(npA3_3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
A2_x = [[1, 2, 3], [4, 5]]
print(A2_x)

[[1, 2, 3], [4, 5]]


In [21]:
npA2_x = np.array(A2_x, dtype=object)
print(A2_x)


[[1, 2, 3], [4, 5]]


Session 3A2

Understand different  dtypes supported by NumPy

The underscore in `np.bool`_ is a convention used in NumPy to avoid name clashes with Python’s built-in types. In Python, bool is the built-in type, so NumPy uses bool_ to denote its own array-compatible Boolean type.

In [22]:
npBool = np.bool_(True)
print('About dtype bool_')
print('Type: ', type(npBool))
print('Size: ', npBool.itemsize)
print('Value: ', npBool)

About dtype bool_
Type:  <class 'numpy.bool_'>
Size:  1
Value:  True


`np.byte` is a NumPy data type that represents an 8-bit signed integer. It can store values between -128 and 127

When you try to store 300 in an 8-bit signed integer, NumPy attempts to fit this value within the allowed range. Since 300 exceeds the maximum allowable value (127), integer overflow occurs, and the result is wrapped around using modulo arithmetic.

After wrapping around, 300 is stored as 44, because 300 - 256 = 44.

Since np.byte is a subclass of NumPy's np.int8 (a signed 8-bit integer), the type will be <class 'numpy.int8'>.

`np.iinfo` is a function that provides information about the limits of integer types

In [23]:
npByte = np.byte(300) # It can only store an 8-bit value
print('\nAbout dtype byte')
print('Type: ', type(npByte))
print('Size: ', npByte.itemsize)
print('Value: ', npByte) 
print('min and max: ', np.iinfo(np.byte).min, np.iinfo(np.byte).max)


About dtype byte
Type:  <class 'numpy.int8'>
Size:  1
Value:  44
min and max:  -128 127


C:\Users\pranav\AppData\Local\Temp\ipykernel_22488\1233506481.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  npByte = np.byte(300) # It can only store an 8-bit value


### Unsigned Integer (`np.ubyte`)
- Unlike signed integers (like `np.byte`), `np.ubyte` can only store non-negative numbers (from **0** to **255**). It uses **8 bits** (1 byte) to represent these values.

### Hexadecimal Input
- `0xFF` in hexadecimal is equivalent to **255** in decimal, which is the maximum value that can be stored in an unsigned 8-bit integer.

### `itemsize`
- Shows that `np.ubyte` takes **1 byte** (8 bits) of memory.

### `np.iinfo()`
- Provides information about the min and max allowable values for NumPy unsigned integer types like `np.ubyte`, with a minimum of **0** and a maximum of **255**.


In [24]:
npUbyte = np.ubyte(0xFF) 
print('\nAbout dtype ubyte')
print('Type: ', type(npUbyte))
print('Size: ', npUbyte.itemsize)
print('Value: ', npUbyte) 
print('min and max: ', np.iinfo(np.ubyte).min, np.iinfo(np.ubyte).max)


About dtype ubyte
Type:  <class 'numpy.uint8'>
Size:  1
Value:  255
min and max:  0 255


`np.short`: Represents a signed 16-bit integer with a range of -32768 to 32767.

`np.iinfo()`: Provides the minimum and maximum values for signed 16-bit integers: -32768 and 32767, respectively

In [25]:

npShort = np.short(0xFFFF)
print('\nAbout dtype short')
print('Type: ', type(npShort))
print('Size: ', npShort.itemsize)
print('Value: ', npShort)
print('min and max: ', np.iinfo(np.short).min, np.iinfo(np.short).max)



About dtype short
Type:  <class 'numpy.int16'>
Size:  2
Value:  -1
min and max:  -32768 32767


C:\Users\pranav\AppData\Local\Temp\ipykernel_22488\2914512378.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 65535 to int16 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  npShort = np.short(0xFFFF)
